# diseases.py
# DOKITA Test Bot — Définition des 60 maladies et profils patients
# Chaque maladie a : profil A (idéal), profil D (cas limite), diagnostic attendu,
# examens obligatoires OMS, médicaments 1ère et 2ème intention

DISEASES = [
  {
    "id": "M1", "nom": "Paludisme simple",
    "profil_A": {"age": 32, "sexe": "F", "poids": 65, "ville": "Brazzaville", "cas_special": "aucun"},
    "profil_D": {"age": 28, "sexe": "F", "poids": 68, "ville": "Brazzaville", "cas_special": "enceinte", "grossesse_trimestre": 2},
    "diagnostic_attendu": "Paludisme",
    "examens_obligatoires": ["TDR paludisme", "Goutte épaisse", "Hémoglobine", "Glycémie capillaire"],
    "medicament_1ere": "Artémether+Luméfantrine 80/480mg 2x/jour 3 jours",
    "medicament_2eme": "Artésunate+Amodiaquine 2cp/jour 3 jours",
    "examen_a_oublier": "Goutte épaisse",
    "contre_indication_profil_D": "Quinine préférable au 1er trimestre"
  },
  {
    "id": "M2", "nom": "Paludisme résistant",
    "profil_A": {"age": 28, "sexe": "H", "poids": 70, "ville": "Kinshasa", "cas_special": "aucun"},
    "profil_D": {"age": 45, "sexe": "H", "poids": 75, "ville": "Kinshasa", "cas_special": "aucun"},
    "diagnostic_attendu": "Paludisme résistant",
    "examens_obligatoires": ["TDR paludisme", "Goutte épaisse", "Frottis sanguin", "Hémoglobine"],
    "medicament_1ere": "Artésunate IV 2.4mg/kg à H0 H12 H24 puis oral",
    "medicament_2eme": "Quinine IV 10mg/kg/8h",
    "examen_a_oublier": "Frottis sanguin",
    "contre_indication_profil_D": "Aucune spécifique"
  },
  {
    "id": "M3", "nom": "Paludisme sévère",
    "profil_A": {"age": 8, "sexe": "H", "poids": 25, "ville": "Abidjan", "cas_special": "enfant"},
    "profil_D": {"age": 3, "sexe": "F", "poids": 13, "ville": "Abidjan", "cas_special": "enfant"},
    "diagnostic_attendu": "Paludisme sévère",
    "examens_obligatoires": ["TDR paludisme", "Goutte épaisse", "NFS", "Glycémie", "Créatinine", "Lactates"],
    "medicament_1ere": "Artésunate IV 3mg/kg < 20kg",
    "medicament_2eme": "Quinine IV 10mg/kg/8h",
    "examen_a_oublier": "Lactates",
    "contre_indication_profil_D": "Adapter dose au poids exact 13kg"
  },
  {
    "id": "M4", "nom": "Typhoïde",
    "profil_A": {"age": 25, "sexe": "H", "poids": 68, "ville": "Dakar", "cas_special": "aucun"},
    "profil_D": {"age": 7, "sexe": "H", "poids": 22, "ville": "Dakar", "cas_special": "enfant"},
    "diagnostic_attendu": "Typhoïde",
    "examens_obligatoires": ["Hémoculture", "NFS", "CRP", "Widal (interpréter avec prudence)"],
    "medicament_1ere": "Azithromycine 1g/jour J1 puis 500mg/jour 6 jours",
    "medicament_2eme": "Ceftriaxone 2g/jour IV 10-14 jours",
    "examen_a_oublier": "Hémoculture",
    "contre_indication_profil_D": "Fluoroquinolones contre-indiquées < 18 ans"
  },
  {
    "id": "M5", "nom": "Méningite bactérienne",
    "profil_A": {"age": 19, "sexe": "F", "poids": 55, "ville": "Bamako", "cas_special": "aucun"},
    "profil_D": {"age": 3, "sexe": "H", "poids": 14, "ville": "Bamako", "cas_special": "enfant"},
    "diagnostic_attendu": "Méningite bactérienne",
    "examens_obligatoires": ["Ponction lombaire", "NFS", "CRP", "Hémoculture", "Glycémie"],
    "medicament_1ere": "Ceftriaxone 100mg/kg/jour (enfant) 2g/12h (adulte) 10 jours",
    "medicament_2eme": "Ampicilline 200mg/kg/jour + Chloramphénicol",
    "examen_a_oublier": "Ponction lombaire",
    "contre_indication_profil_D": "Dexaméthasone à associer pour réduire séquelles"
  },
  {
    "id": "M6", "nom": "Tuberculose pulmonaire",
    "profil_A": {"age": 35, "sexe": "H", "poids": 58, "ville": "Lomé", "cas_special": "aucun"},
    "profil_D": {"age": 38, "sexe": "H", "poids": 55, "ville": "Lomé", "cas_special": "VIH+", "cd4": 150},
    "diagnostic_attendu": "Tuberculose",
    "examens_obligatoires": ["Bacilloscopie crachats × 3", "Rx thorax", "Test VIH", "NFS", "Transaminases"],
    "medicament_1ere": "RHZE 2 mois puis RH 4 mois (selon poids)",
    "medicament_2eme": "Protocole résistance si échec",
    "examen_a_oublier": "Transaminases",
    "contre_indication_profil_D": "Commencer TB d'abord puis ARV 2-8 semaines après"
  },
  {
    "id": "M7", "nom": "VIH primo-infection",
    "profil_A": {"age": 22, "sexe": "F", "poids": 60, "ville": "Cotonou", "cas_special": "aucun"},
    "profil_D": {"age": 35, "sexe": "F", "poids": 62, "ville": "Cotonou", "cas_special": "enceinte", "grossesse_trimestre": 1},
    "diagnostic_attendu": "VIH",
    "examens_obligatoires": ["Test VIH rapide", "Charge virale", "CD4", "NFS", "Créatinine", "Transaminases"],
    "medicament_1ere": "TDF+3TC+DTG (Tenofovir+Lamivudine+Dolutégravir)",
    "medicament_2eme": "TDF+3TC+EFV (Efavirenz)",
    "examen_a_oublier": "Charge virale",
    "contre_indication_profil_D": "DTG préférable pendant grossesse — Efavirenz possible T2-T3"
  },
  {
    "id": "M8", "nom": "VIH + Tuberculose",
    "profil_A": {"age": 40, "sexe": "H", "poids": 55, "ville": "Accra", "cas_special": "VIH+", "cd4": 80},
    "profil_D": {"age": 28, "sexe": "F", "poids": 50, "ville": "Accra", "cas_special": "VIH+", "cd4": 50},
    "diagnostic_attendu": "Tuberculose VIH",
    "examens_obligatoires": ["Bacilloscopie", "CD4", "Charge virale", "Rx thorax", "Transaminases", "NFS"],
    "medicament_1ere": "RHZE puis RH + TDF+3TC+EFV (après 2-8 semaines TB)",
    "medicament_2eme": "Protocole alternatif si intolérance",
    "examen_a_oublier": "CD4",
    "contre_indication_profil_D": "Cotrimoxazole prophylaxie obligatoire si CD4 < 200"
  },
  {
    "id": "M9", "nom": "Dengue",
    "profil_A": {"age": 30, "sexe": "F", "poids": 62, "ville": "Abidjan", "cas_special": "aucun"},
    "profil_D": {"age": 67, "sexe": "F", "poids": 65, "ville": "Abidjan", "cas_special": "aucun"},
    "diagnostic_attendu": "Dengue",
    "examens_obligatoires": ["NFS + plaquettes", "Hématocrite", "NS1 ou sérologie dengue", "Transaminases"],
    "medicament_1ere": "Traitement symptomatique : Paracétamol + réhydratation orale",
    "medicament_2eme": "Hospitalisation si dengue sévère + remplissage prudent",
    "examen_a_oublier": "Hématocrite",
    "contre_indication_profil_D": "Aspirine et AINS contre-indiqués — risque hémorragique"
  },
  {
    "id": "M10", "nom": "Dengue sévère",
    "profil_A": {"age": 45, "sexe": "H", "poids": 80, "ville": "Lagos", "cas_special": "aucun"},
    "profil_D": {"age": 8, "sexe": "H", "poids": 26, "ville": "Lagos", "cas_special": "enfant"},
    "diagnostic_attendu": "Dengue sévère",
    "examens_obligatoires": ["NFS + plaquettes", "Hématocrite", "NS1", "Transaminases", "Coagulation", "Groupe sanguin"],
    "medicament_1ere": "Hospitalisation + remplissage sérum physiologique 10ml/kg",
    "medicament_2eme": "Transfusion plaquettaire si < 10 000/mm3 avec saignement",
    "examen_a_oublier": "Coagulation",
    "contre_indication_profil_D": "Volume remplissage adapté au poids enfant"
  },
  {
    "id": "M11", "nom": "Choléra",
    "profil_A": {"age": 28, "sexe": "F", "poids": 58, "ville": "Niamey", "cas_special": "aucun"},
    "profil_D": {"age": 2, "sexe": "H", "poids": 11, "ville": "Niamey", "cas_special": "enfant"},
    "diagnostic_attendu": "Choléra",
    "examens_obligatoires": ["Coproculture", "Ionogramme", "Créatinine", "Glycémie"],
    "medicament_1ere": "SRO 75ml/kg en 4h (plan C) + Doxycycline 300mg dose unique adulte",
    "medicament_2eme": "Azithromycine 20mg/kg dose unique enfant",
    "examen_a_oublier": "Ionogramme",
    "contre_indication_profil_D": "Doxycycline contre-indiquée < 8 ans — Azithromycine ou Cotrimoxazole"
  },
  {
    "id": "M12", "nom": "Diarrhée aiguë",
    "profil_A": {"age": 3, "sexe": "F", "poids": 14, "ville": "Ouagadougou", "cas_special": "enfant"},
    "profil_D": {"age": 1, "sexe": "H", "poids": 9, "ville": "Ouagadougou", "cas_special": "enfant"},
    "diagnostic_attendu": "Diarrhée aiguë",
    "examens_obligatoires": ["Coproculture si sang", "Ionogramme si déshydratation sévère"],
    "medicament_1ere": "SRO + Zinc 20mg/jour 10-14 jours",
    "medicament_2eme": "Cotrimoxazole si dysenterie confirmée",
    "examen_a_oublier": "Ionogramme",
    "contre_indication_profil_D": "Volume SRO adapté : 9kg → plan selon degré déshydratation"
  },
  {
    "id": "M13", "nom": "Pneumonie communautaire",
    "profil_A": {"age": 50, "sexe": "H", "poids": 75, "ville": "Yaoundé", "cas_special": "aucun"},
    "profil_D": {"age": 52, "sexe": "H", "poids": 88, "ville": "Yaoundé", "cas_special": "diabetique"},
    "diagnostic_attendu": "Pneumonie",
    "examens_obligatoires": ["Rx thorax", "NFS", "CRP", "Hémoculture", "Oxymétrie"],
    "medicament_1ere": "Amoxicilline-Acide clavulanique 1g × 3/jour 7 jours",
    "medicament_2eme": "Ceftriaxone 2g/jour IV si hospitalisé",
    "examen_a_oublier": "Hémoculture",
    "contre_indication_profil_D": "Glycémie à surveiller sous corticoïdes"
  },
  {
    "id": "M14", "nom": "Pneumonie enfant",
    "profil_A": {"age": 1, "sexe": "F", "poids": 10, "ville": "Douala", "cas_special": "enfant"},
    "profil_D": {"age": 0, "sexe": "H", "poids": 5, "ville": "Douala", "cas_special": "enfant", "mois": 6},
    "diagnostic_attendu": "Pneumonie",
    "examens_obligatoires": ["Rx thorax", "Oxymétrie", "NFS"],
    "medicament_1ere": "Amoxicilline 90mg/kg/jour 5 jours",
    "medicament_2eme": "Ampicilline IV + Gentamicine si grave",
    "examen_a_oublier": "Oxymétrie",
    "contre_indication_profil_D": "Dose Amoxicilline 90mg/kg/jour pour 5kg = 450mg/jour"
  },
  {
    "id": "M15", "nom": "Typhoïde enfant",
    "profil_A": {"age": 7, "sexe": "F", "poids": 22, "ville": "Dakar", "cas_special": "enfant"},
    "profil_D": {"age": 10, "sexe": "H", "poids": 30, "ville": "Dakar", "cas_special": "enfant"},
    "diagnostic_attendu": "Typhoïde",
    "examens_obligatoires": ["Hémoculture", "NFS", "CRP"],
    "medicament_1ere": "Azithromycine 20mg/kg/jour 7 jours",
    "medicament_2eme": "Ceftriaxone 50mg/kg/jour IV",
    "examen_a_oublier": "Hémoculture",
    "contre_indication_profil_D": "Fluoroquinolones interdites < 18 ans"
  },
  {
    "id": "M16", "nom": "Méningite méningocoque",
    "profil_A": {"age": 16, "sexe": "H", "poids": 60, "ville": "Ouagadougou", "cas_special": "aucun"},
    "profil_D": {"age": 4, "sexe": "F", "poids": 16, "ville": "Ouagadougou", "cas_special": "enfant"},
    "diagnostic_attendu": "Méningite bactérienne",
    "examens_obligatoires": ["Ponction lombaire", "NFS", "CRP", "Hémoculture"],
    "medicament_1ere": "Ceftriaxone 100mg/kg/jour enfant 2g/12h adulte",
    "medicament_2eme": "Chloramphénicol huileux 100mg/kg dose unique si épidémie",
    "examen_a_oublier": "Hémoculture",
    "contre_indication_profil_D": "Dexaméthasone avant ou avec 1ère dose ATB"
  },
  {
    "id": "M17", "nom": "Angine streptococcique",
    "profil_A": {"age": 24, "sexe": "F", "poids": 58, "ville": "Abidjan", "cas_special": "aucun"},
    "profil_D": {"age": 35, "sexe": "F", "poids": 62, "ville": "Abidjan", "cas_special": "allergie", "allergie": "pénicilline"},
    "diagnostic_attendu": "Angine",
    "examens_obligatoires": ["TDR streptocoque", "NFS si doute"],
    "medicament_1ere": "Amoxicilline 1g × 2/jour 6 jours",
    "medicament_2eme": "Azithromycine 500mg/jour 3 jours",
    "examen_a_oublier": "TDR streptocoque",
    "contre_indication_profil_D": "Amoxicilline contre-indiquée allergie pénicilline → Azithromycine"
  },
  {
    "id": "M18", "nom": "Paludisme grossesse",
    "profil_A": {"age": 28, "sexe": "F", "poids": 70, "ville": "Brazzaville", "cas_special": "enceinte", "grossesse_trimestre": 3},
    "profil_D": {"age": 17, "sexe": "F", "poids": 58, "ville": "Brazzaville", "cas_special": "enceinte", "grossesse_trimestre": 1},
    "diagnostic_attendu": "Paludisme",
    "examens_obligatoires": ["TDR paludisme", "Goutte épaisse", "Hémoglobine", "Glycémie", "Échographie obstétricale"],
    "medicament_1ere": "Quinine T1 · AL T2-T3",
    "medicament_2eme": "Artésunate IV si grave",
    "examen_a_oublier": "Échographie obstétricale",
    "contre_indication_profil_D": "Artémisinine évitée au T1 — Quinine 1ère intention"
  },
  {
    "id": "M19", "nom": "Brucellose",
    "profil_A": {"age": 38, "sexe": "H", "poids": 72, "ville": "Bamako", "cas_special": "aucun"},
    "profil_D": {"age": 65, "sexe": "H", "poids": 68, "ville": "Bamako", "cas_special": "aucun"},
    "diagnostic_attendu": "Brucellose",
    "examens_obligatoires": ["Sérologie Brucella", "Hémoculture", "NFS", "Transaminases"],
    "medicament_1ere": "Doxycycline 200mg/jour 6 semaines + Rifampicine 600mg/jour",
    "medicament_2eme": "Doxycycline + Streptomycine 1g/jour IM 2-3 semaines",
    "examen_a_oublier": "Hémoculture",
    "contre_indication_profil_D": "Aucune spécifique"
  },
  {
    "id": "M20", "nom": "Leptospirose",
    "profil_A": {"age": 29, "sexe": "H", "poids": 68, "ville": "Kinshasa", "cas_special": "aucun"},
    "profil_D": {"age": 42, "sexe": "H", "poids": 74, "ville": "Kinshasa", "cas_special": "aucun"},
    "diagnostic_attendu": "Leptospirose",
    "examens_obligatoires": ["Sérologie MAT", "NFS", "Créatinine", "Transaminases", "CPK", "BU + ECBU"],
    "medicament_1ere": "Doxycycline 200mg/jour 7 jours forme légère",
    "medicament_2eme": "Pénicilline G 1.5MU/6h IV forme sévère",
    "examen_a_oublier": "CPK",
    "contre_indication_profil_D": "Surveillance rénale si insuffisance"
  },
  {
    "id": "M21", "nom": "Rickettsiose",
    "profil_A": {"age": 44, "sexe": "H", "poids": 74, "ville": "Nairobi", "cas_special": "aucun"},
    "profil_D": {"age": 60, "sexe": "F", "poids": 66, "ville": "Nairobi", "cas_special": "aucun"},
    "diagnostic_attendu": "Rickettsiose",
    "examens_obligatoires": ["Sérologie Rickettsia", "NFS", "CRP", "Transaminases"],
    "medicament_1ere": "Doxycycline 200mg/jour 7-10 jours",
    "medicament_2eme": "Chloramphénicol si contre-indication doxycycline",
    "examen_a_oublier": "Sérologie Rickettsia",
    "contre_indication_profil_D": "Aucune spécifique"
  },
  {
    "id": "M22", "nom": "Trypanosomiase",
    "profil_A": {"age": 35, "sexe": "F", "poids": 62, "ville": "Brazzaville", "cas_special": "aucun"},
    "profil_D": {"age": 12, "sexe": "H", "poids": 38, "ville": "Brazzaville", "cas_special": "aucun"},
    "diagnostic_attendu": "Trypanosomiase",
    "examens_obligatoires": ["Test sérologique CATT", "Parasitologie sang", "PL si stade 2", "NFS"],
    "medicament_1ere": "Pentamidine stade 1 · Éflornithine + Nifurtimox stade 2",
    "medicament_2eme": "Mélarsoprol si échec (toxique)",
    "examen_a_oublier": "PL si stade 2",
    "contre_indication_profil_D": "Adapter dose au poids enfant"
  },
  {
    "id": "M23", "nom": "Leishmaniose cutanée",
    "profil_A": {"age": 31, "sexe": "H", "poids": 70, "ville": "Bamako", "cas_special": "aucun"},
    "profil_D": {"age": 55, "sexe": "H", "poids": 72, "ville": "Bamako", "cas_special": "aucun"},
    "diagnostic_attendu": "Leishmaniose",
    "examens_obligatoires": ["Frottis de la lésion", "PCR Leishmania", "Test de Montenegro"],
    "medicament_1ere": "Antimoniate de méglumine intralesionnel ou systémique",
    "medicament_2eme": "Amphotéricine B liposomale",
    "examen_a_oublier": "PCR Leishmania",
    "contre_indication_profil_D": "Surveillance cardiaque sous antimoniate"
  },
  {
    "id": "M24", "nom": "Schistosomiase",
    "profil_A": {"age": 10, "sexe": "H", "poids": 30, "ville": "Niamey", "cas_special": "enfant"},
    "profil_D": {"age": 8, "sexe": "F", "poids": 24, "ville": "Niamey", "cas_special": "enfant"},
    "diagnostic_attendu": "Schistosomiase",
    "examens_obligatoires": ["Parasitologie urine + selles", "Sérologie schistosomiase", "NFS", "Échographie abdominale"],
    "medicament_1ere": "Praziquantel 40mg/kg dose unique",
    "medicament_2eme": "Praziquantel 60mg/kg si S. japonicum",
    "examen_a_oublier": "Échographie abdominale",
    "contre_indication_profil_D": "Praziquantel déconseillé < 4 ans — adapter"
  },
  {
    "id": "M25", "nom": "Onchocercose",
    "profil_A": {"age": 42, "sexe": "H", "poids": 68, "ville": "Ouagadougou", "cas_special": "aucun"},
    "profil_D": {"age": 58, "sexe": "H", "poids": 65, "ville": "Ouagadougou", "cas_special": "aucun"},
    "diagnostic_attendu": "Onchocercose",
    "examens_obligatoires": ["Biopsie cutanée exsangue", "Sérologie onchocercose", "Examen oculaire à la lampe à fente"],
    "medicament_1ere": "Ivermectine 150mcg/kg dose unique annuelle",
    "medicament_2eme": "Doxycycline 100mg/jour 6 semaines (anti-Wolbachia)",
    "examen_a_oublier": "Examen oculaire",
    "contre_indication_profil_D": "Ivermectine contre-indiquée si zone Loa loa (MEG > 8000/ml)"
  },
  {
    "id": "M26", "nom": "Rougeole",
    "profil_A": {"age": 1, "sexe": "H", "poids": 10, "ville": "Lomé", "cas_special": "enfant", "mois": 14},
    "profil_D": {"age": 0, "sexe": "F", "poids": 7, "ville": "Lomé", "cas_special": "enfant", "mois": 9},
    "diagnostic_attendu": "Rougeole",
    "examens_obligatoires": ["Sérologie IgM rougeole", "NFS", "Rx thorax si fièvre > 3j"],
    "medicament_1ere": "Vitamine A 200 000 UI 2 jours si > 12 mois",
    "medicament_2eme": "Vitamine A 100 000 UI si 6-11 mois · ATB si surinfection",
    "examen_a_oublier": "Rx thorax",
    "contre_indication_profil_D": "Vitamine A 50 000 UI si < 6 mois"
  },
  {
    "id": "M27", "nom": "Tétanos",
    "profil_A": {"age": 55, "sexe": "H", "poids": 72, "ville": "Cotonou", "cas_special": "aucun"},
    "profil_D": {"age": 0, "sexe": "H", "poids": 3, "ville": "Cotonou", "cas_special": "enfant", "mois": 1},
    "diagnostic_attendu": "Tétanos",
    "examens_obligatoires": ["Diagnostic clinique", "NFS", "Ionogramme"],
    "medicament_1ere": "Immunoglobulines tétaniques 3000-6000 UI IM + Métronidazole 500mg/8h",
    "medicament_2eme": "Pénicilline G 100 000 UI/kg/jour",
    "examen_a_oublier": "Ionogramme",
    "contre_indication_profil_D": "Tétanos néonatal : protocole spécifique"
  },
  {
    "id": "M28", "nom": "Coqueluche",
    "profil_A": {"age": 0, "sexe": "H", "poids": 5, "ville": "Ouagadougou", "cas_special": "enfant", "mois": 3},
    "profil_D": {"age": 0, "sexe": "F", "poids": 4, "ville": "Ouagadougou", "cas_special": "enfant", "mois": 6},
    "diagnostic_attendu": "Coqueluche",
    "examens_obligatoires": ["PCR coqueluche nasopharyngée", "NFS", "Oxymétrie", "Rx thorax"],
    "medicament_1ere": "Azithromycine 10mg/kg/jour 5 jours nourrisson",
    "medicament_2eme": "Cotrimoxazole si allergie macrolide",
    "examen_a_oublier": "PCR coqueluche",
    "contre_indication_profil_D": "Hospitalisation systématique < 6 mois"
  },
  {
    "id": "M29", "nom": "Diphtérie",
    "profil_A": {"age": 6, "sexe": "H", "poids": 20, "ville": "Dakar", "cas_special": "enfant"},
    "profil_D": {"age": 4, "sexe": "F", "poids": 16, "ville": "Dakar", "cas_special": "enfant"},
    "diagnostic_attendu": "Diphtérie",
    "examens_obligatoires": ["Prélèvement gorge culture", "ECG", "NFS", "Créatinine"],
    "medicament_1ere": "Sérum antidiphtérique 20 000-100 000 UI selon forme + Pénicilline G 100 000 UI/kg/jour",
    "medicament_2eme": "Érythromycine 40mg/kg/jour si allergie pénicilline",
    "examen_a_oublier": "ECG",
    "contre_indication_profil_D": "Dose sérum adaptée selon localisation et durée"
  },
  {
    "id": "M30", "nom": "Mpox",
    "profil_A": {"age": 27, "sexe": "H", "poids": 71, "ville": "Kinshasa", "cas_special": "aucun"},
    "profil_D": {"age": 5, "sexe": "H", "poids": 18, "ville": "Kinshasa", "cas_special": "enfant"},
    "diagnostic_attendu": "Mpox",
    "examens_obligatoires": ["PCR Mpox sur lésion", "Test VIH", "NFS"],
    "medicament_1ere": "Traitement symptomatique + isolement · Tecovirimat si disponible",
    "medicament_2eme": "Cidofovir si immunodéprimé",
    "examen_a_oublier": "Test VIH",
    "contre_indication_profil_D": "Vaccin Jynneos si disponible"
  },
  {
    "id": "M31", "nom": "Fièvre jaune",
    "profil_A": {"age": 33, "sexe": "H", "poids": 74, "ville": "Abidjan", "cas_special": "aucun"},
    "profil_D": {"age": 62, "sexe": "H", "poids": 70, "ville": "Abidjan", "cas_special": "aucun"},
    "diagnostic_attendu": "Fièvre jaune",
    "examens_obligatoires": ["Sérologie IgM fièvre jaune", "NFS", "Transaminases", "Bilirubine", "TP"],
    "medicament_1ere": "Traitement symptomatique + réanimation si sévère",
    "medicament_2eme": "Pas de traitement spécifique antiviral validé",
    "examen_a_oublier": "TP",
    "contre_indication_profil_D": "Surveillance hépatique rapprochée"
  },
  {
    "id": "M32", "nom": "Hépatite B aiguë",
    "profil_A": {"age": 26, "sexe": "F", "poids": 59, "ville": "Lagos", "cas_special": "aucun"},
    "profil_D": {"age": 28, "sexe": "F", "poids": 65, "ville": "Lagos", "cas_special": "enceinte", "grossesse_trimestre": 2},
    "diagnostic_attendu": "Hépatite",
    "examens_obligatoires": ["AgHBs", "Ac anti-HBc IgM", "Transaminases", "Bilirubine", "TP", "NFS"],
    "medicament_1ere": "Traitement symptomatique + repos + surveillance",
    "medicament_2eme": "Ténofovir si fulminant ou immunodéprimé",
    "examen_a_oublier": "TP",
    "contre_indication_profil_D": "Ténofovir possible pendant grossesse si nécessaire"
  },
  {
    "id": "M33", "nom": "Hépatite C",
    "profil_A": {"age": 48, "sexe": "H", "poids": 76, "ville": "Kinshasa", "cas_special": "aucun"},
    "profil_D": {"age": 65, "sexe": "H", "poids": 72, "ville": "Kinshasa", "cas_special": "aucun"},
    "diagnostic_attendu": "Hépatite",
    "examens_obligatoires": ["Ac anti-VHC", "ARN VHC", "Transaminases", "Échographie hépatique", "NFS"],
    "medicament_1ere": "Sofosbuvir+Daclatasvir 12 semaines si disponible",
    "medicament_2eme": "Sofosbuvir+Ribavirine selon génotype",
    "examen_a_oublier": "Échographie hépatique",
    "contre_indication_profil_D": "Surveillance hépatique si cirrhose"
  },
  {
    "id": "M34", "nom": "Diabète type 2",
    "profil_A": {"age": 52, "sexe": "H", "poids": 88, "ville": "Abidjan", "cas_special": "aucun"},
    "profil_D": {"age": 58, "sexe": "F", "poids": 92, "ville": "Abidjan", "cas_special": "aucun"},
    "diagnostic_attendu": "Diabète",
    "examens_obligatoires": ["Glycémie à jeun", "HbA1c", "Créatinine", "Lipides", "Fond d'oeil", "ECG"],
    "medicament_1ere": "Metformine 500mg × 2/jour puis titration",
    "medicament_2eme": "Glibenclamide 2.5mg/jour si metformine insuffisante",
    "examen_a_oublier": "Fond d'oeil",
    "contre_indication_profil_D": "Metformine contre-indiquée si DFG < 30"
  },
  {
    "id": "M35", "nom": "Hypertension artérielle",
    "profil_A": {"age": 58, "sexe": "F", "poids": 82, "ville": "Brazzaville", "cas_special": "aucun"},
    "profil_D": {"age": 65, "sexe": "F", "poids": 78, "ville": "Brazzaville", "cas_special": "aucun"},
    "diagnostic_attendu": "Hypertension",
    "examens_obligatoires": ["TA × 3 mesures", "Créatinine", "Ionogramme", "ECG", "Fond d'oeil", "BU"],
    "medicament_1ere": "Amlodipine 5mg/jour ou Losartan 50mg/jour",
    "medicament_2eme": "Hydrochlorothiazide 12.5mg/jour en association",
    "examen_a_oublier": "Fond d'oeil",
    "contre_indication_profil_D": "IEC contre-indiqués si insuffisance rénale avancée"
  },
  {
    "id": "M36", "nom": "Drépanocytose crise",
    "profil_A": {"age": 22, "sexe": "H", "poids": 65, "ville": "Accra", "cas_special": "drepano"},
    "profil_D": {"age": 14, "sexe": "F", "poids": 45, "ville": "Accra", "cas_special": "drepano"},
    "diagnostic_attendu": "Drépanocytose",
    "examens_obligatoires": ["NFS + réticulocytes", "Hémoglobine", "LDH", "Bilirubine", "Groupage"],
    "medicament_1ere": "Morphine 0.1mg/kg IV + Paracétamol + réhydratation",
    "medicament_2eme": "Kétoprofène IV si morphine insuffisante",
    "examen_a_oublier": "LDH",
    "contre_indication_profil_D": "AINS contre-indiqués si atteinte rénale"
  },
  {
    "id": "M37", "nom": "Diabète + infection",
    "profil_A": {"age": 45, "sexe": "F", "poids": 79, "ville": "Dakar", "cas_special": "diabetique"},
    "profil_D": {"age": 62, "sexe": "H", "poids": 85, "ville": "Dakar", "cas_special": "diabetique"},
    "diagnostic_attendu": "Infection",
    "examens_obligatoires": ["Glycémie", "NFS", "CRP", "ECBU", "Hémoculture", "Rx pied si plaie"],
    "medicament_1ere": "Amoxicilline-Acide clavulanique + Metronidazole si pied diabétique",
    "medicament_2eme": "Ceftriaxone + Métronidazole si sévère",
    "examen_a_oublier": "Hémoculture",
    "contre_indication_profil_D": "Contrôle glycémie strict — adapter insuline"
  },
  {
    "id": "M38", "nom": "Épilepsie",
    "profil_A": {"age": 34, "sexe": "H", "poids": 72, "ville": "Lomé", "cas_special": "aucun"},
    "profil_D": {"age": 28, "sexe": "F", "poids": 60, "ville": "Lomé", "cas_special": "enceinte", "grossesse_trimestre": 2},
    "diagnostic_attendu": "Épilepsie",
    "examens_obligatoires": ["EEG", "IRM cérébrale", "NFS", "Ionogramme", "Glycémie", "Transaminases"],
    "medicament_1ere": "Carbamazépine 200mg × 2/jour titration",
    "medicament_2eme": "Valproate 500mg/jour (contre-indiqué grossesse)",
    "examen_a_oublier": "IRM cérébrale",
    "contre_indication_profil_D": "Valproate contre-indiqué grossesse — Lamotrigine préférable"
  },
  {
    "id": "M39", "nom": "Insuffisance cardiaque",
    "profil_A": {"age": 65, "sexe": "H", "poids": 78, "ville": "Yaoundé", "cas_special": "aucun"},
    "profil_D": {"age": 72, "sexe": "F", "poids": 74, "ville": "Yaoundé", "cas_special": "aucun"},
    "diagnostic_attendu": "Insuffisance cardiaque",
    "examens_obligatoires": ["ECG", "Rx thorax", "BNP ou NT-proBNP", "Échographie cardiaque", "Créatinine", "Ionogramme"],
    "medicament_1ere": "Furosémide 40mg/jour + IEC Enalapril 5mg",
    "medicament_2eme": "Spironolactone 25mg/jour en association",
    "examen_a_oublier": "BNP",
    "contre_indication_profil_D": "IEC contre-indiqué si hyperkaliémie"
  },
  {
    "id": "M40", "nom": "Asthme crise",
    "profil_A": {"age": 29, "sexe": "F", "poids": 63, "ville": "Abidjan", "cas_special": "aucun"},
    "profil_D": {"age": 32, "sexe": "F", "poids": 67, "ville": "Abidjan", "cas_special": "enceinte", "grossesse_trimestre": 2},
    "diagnostic_attendu": "Asthme",
    "examens_obligatoires": ["Oxymétrie", "DEP si possible", "Rx thorax si 1ère crise"],
    "medicament_1ere": "Salbutamol 2.5mg nébulisation × 3 + Prednisolone 1mg/kg",
    "medicament_2eme": "Ipratropium 0.5mg nébulisation + Salbutamol si sévère",
    "examen_a_oublier": "DEP",
    "contre_indication_profil_D": "Bêta-2 agonistes et corticoïdes systémiques autorisés pendant grossesse"
  },
  {
    "id": "M41", "nom": "BPCO exacerbation",
    "profil_A": {"age": 60, "sexe": "H", "poids": 74, "ville": "Bamako", "cas_special": "aucun"},
    "profil_D": {"age": 68, "sexe": "H", "poids": 66, "ville": "Bamako", "cas_special": "aucun"},
    "diagnostic_attendu": "BPCO",
    "examens_obligatoires": ["Oxymétrie", "Gazométrie si SaO2 < 92%", "Rx thorax", "NFS", "CRP"],
    "medicament_1ere": "Salbutamol + Ipratropium nébulisation + Prednisolone 40mg/jour 5 jours",
    "medicament_2eme": "Amoxicilline-Acide clavulanique si expectorations purulentes",
    "examen_a_oublier": "Gazométrie",
    "contre_indication_profil_D": "O2 contrôlé — cible SaO2 88-92%"
  },
  {
    "id": "M42", "nom": "Malnutrition MAS",
    "profil_A": {"age": 1, "sexe": "H", "poids": 7, "ville": "Niamey", "cas_special": "enfant", "mois": 18},
    "profil_D": {"age": 0, "sexe": "F", "poids": 5, "ville": "Niamey", "cas_special": "enfant", "mois": 10},
    "diagnostic_attendu": "Malnutrition",
    "examens_obligatoires": ["MUAC", "Poids/Taille Z-score", "Glycémie", "Hémoglobine", "Test VIH"],
    "medicament_1ere": "ATPE (Aliment Thérapeutique Prêt à l'Emploi) 150-220ml/kg/jour",
    "medicament_2eme": "F75 puis F100 si complications",
    "examen_a_oublier": "Test VIH",
    "contre_indication_profil_D": "Phase initiale prudente F75 — pas d'ATPE si complications"
  },
  {
    "id": "M43", "nom": "Malnutrition MAM",
    "profil_A": {"age": 2, "sexe": "F", "poids": 9, "ville": "Ouagadougou", "cas_special": "enfant", "mois": 24},
    "profil_D": {"age": 3, "sexe": "H", "poids": 12, "ville": "Ouagadougou", "cas_special": "enfant"},
    "diagnostic_attendu": "Malnutrition",
    "examens_obligatoires": ["MUAC", "Poids/Taille", "Hémoglobine", "Parasitologie selles"],
    "medicament_1ere": "Supplément Plumpy'Sup + Vitamine A + Zinc + Déparasitage",
    "medicament_2eme": "Référence si passage MAS",
    "examen_a_oublier": "Parasitologie selles",
    "contre_indication_profil_D": "Albendazole 200mg si > 12 mois"
  },
  {
    "id": "M44", "nom": "Anémie sévère",
    "profil_A": {"age": 28, "sexe": "F", "poids": 54, "ville": "Kinshasa", "cas_special": "enceinte", "grossesse_trimestre": 3},
    "profil_D": {"age": 6, "sexe": "H", "poids": 20, "ville": "Kinshasa", "cas_special": "enfant"},
    "diagnostic_attendu": "Anémie",
    "examens_obligatoires": ["NFS", "Réticulocytes", "Frottis sanguin", "Ferritine", "TDR paludisme", "Groupage"],
    "medicament_1ere": "Transfusion si Hb < 7g/dl + Fer + Acide folique",
    "medicament_2eme": "Traiter cause : paludisme, parasites, carence",
    "examen_a_oublier": "Réticulocytes",
    "contre_indication_profil_D": "Seuil transfusion Hb < 8 pendant grossesse"
  },
  {
    "id": "M45", "nom": "IST Syphilis",
    "profil_A": {"age": 31, "sexe": "H", "poids": 73, "ville": "Lagos", "cas_special": "aucun"},
    "profil_D": {"age": 25, "sexe": "F", "poids": 60, "ville": "Lagos", "cas_special": "enceinte", "grossesse_trimestre": 2},
    "diagnostic_attendu": "Syphilis",
    "examens_obligatoires": ["RPR + TPHA", "Test VIH", "NFS"],
    "medicament_1ere": "Benzathine Pénicilline G 2.4 MUI IM dose unique",
    "medicament_2eme": "Doxycycline 100mg × 2/jour 14 jours si allergie pénicilline",
    "examen_a_oublier": "Test VIH",
    "contre_indication_profil_D": "Doxycycline contre-indiquée grossesse — désensibilisation pénicilline"
  },
  {
    "id": "M46", "nom": "IST Gonorrhée",
    "profil_A": {"age": 23, "sexe": "F", "poids": 57, "ville": "Abidjan", "cas_special": "aucun"},
    "profil_D": {"age": 19, "sexe": "F", "poids": 53, "ville": "Abidjan", "cas_special": "aucun"},
    "diagnostic_attendu": "IST",
    "examens_obligatoires": ["Prélèvement + culture", "Test VIH", "Sérologie syphilis"],
    "medicament_1ere": "Ceftriaxone 500mg IM dose unique + Azithromycine 1g dose unique",
    "medicament_2eme": "Ciprofloxacine 500mg si sensible (résistances croissantes)",
    "examen_a_oublier": "Sérologie syphilis",
    "contre_indication_profil_D": "Traiter partenaire simultanément"
  },
  {
    "id": "M47", "nom": "Infection urinaire",
    "profil_A": {"age": 35, "sexe": "F", "poids": 64, "ville": "Dakar", "cas_special": "enceinte", "grossesse_trimestre": 1},
    "profil_D": {"age": 70, "sexe": "F", "poids": 62, "ville": "Dakar", "cas_special": "aucun"},
    "diagnostic_attendu": "Infection urinaire",
    "examens_obligatoires": ["BU + ECBU", "NFS", "Créatinine", "Échographie rénale si récidive"],
    "medicament_1ere": "Nitrofurantoïne 100mg × 2/jour 7 jours (sauf T3)",
    "medicament_2eme": "Fosfomycine 3g dose unique si cystite simple",
    "examen_a_oublier": "Créatinine",
    "contre_indication_profil_D": "Nitrofurantoïne contre-indiquée T3 — Fosfomycine ou Amoxicilline"
  },
  {
    "id": "M48", "nom": "Infections génitales hautes",
    "profil_A": {"age": 27, "sexe": "F", "poids": 60, "ville": "Cotonou", "cas_special": "aucun"},
    "profil_D": {"age": 19, "sexe": "F", "poids": 55, "ville": "Cotonou", "cas_special": "aucun"},
    "diagnostic_attendu": "IGH",
    "examens_obligatoires": ["Prélèvements cervicaux", "Test VIH", "Test grossesse", "Échographie pelvienne", "NFS"],
    "medicament_1ere": "Ceftriaxone 500mg IM + Doxycycline 100mg × 2/jour 14 jours + Métronidazole 500mg × 2/jour",
    "medicament_2eme": "Amoxicilline-Acide clavulanique + Métronidazole si ambulatoire",
    "examen_a_oublier": "Échographie pelvienne",
    "contre_indication_profil_D": "Test grossesse AVANT tout traitement"
  },
  {
    "id": "M49", "nom": "Gale",
    "profil_A": {"age": 19, "sexe": "H", "poids": 66, "ville": "Ouagadougou", "cas_special": "aucun"},
    "profil_D": {"age": 5, "sexe": "F", "poids": 18, "ville": "Ouagadougou", "cas_special": "enfant"},
    "diagnostic_attendu": "Gale",
    "examens_obligatoires": ["Examen clinique", "Grattage + microscopie si doute"],
    "medicament_1ere": "Ivermectine 200mcg/kg dose unique à répéter J8",
    "medicament_2eme": "Benzoate de benzyle 25% application locale 3 nuits",
    "examen_a_oublier": "Grattage microscopie",
    "contre_indication_profil_D": "Ivermectine contre-indiquée < 15kg — Benzoate de benzyle 12.5%"
  },
  {
    "id": "M50", "nom": "Impétigo",
    "profil_A": {"age": 5, "sexe": "H", "poids": 18, "ville": "Bamako", "cas_special": "enfant"},
    "profil_D": {"age": 3, "sexe": "F", "poids": 13, "ville": "Bamako", "cas_special": "enfant"},
    "diagnostic_attendu": "Impétigo",
    "examens_obligatoires": ["Examen clinique", "Prélèvement + culture si étendu"],
    "medicament_1ere": "Acide fusidique crème 3 × /jour 7 jours si localisé",
    "medicament_2eme": "Amoxicilline-Acide clavulanique si étendu",
    "examen_a_oublier": "Culture",
    "contre_indication_profil_D": "Aucune spécifique"
  },
  {
    "id": "M51", "nom": "Érysipèle",
    "profil_A": {"age": 49, "sexe": "F", "poids": 76, "ville": "Abidjan", "cas_special": "aucun"},
    "profil_D": {"age": 55, "sexe": "F", "poids": 80, "ville": "Abidjan", "cas_special": "diabetique"},
    "diagnostic_attendu": "Érysipèle",
    "examens_obligatoires": ["Examen clinique", "NFS", "CRP", "Créatinine", "Glycémie si diabétique"],
    "medicament_1ere": "Amoxicilline 3g/jour 10-20 jours",
    "medicament_2eme": "Pristinamycine si allergie pénicilline",
    "examen_a_oublier": "Créatinine",
    "contre_indication_profil_D": "Surveillance glycémie sous ATB"
  },
  {
    "id": "M52", "nom": "Amibiase hépatique",
    "profil_A": {"age": 38, "sexe": "H", "poids": 74, "ville": "Kinshasa", "cas_special": "aucun"},
    "profil_D": {"age": 52, "sexe": "H", "poids": 78, "ville": "Kinshasa", "cas_special": "aucun"},
    "diagnostic_attendu": "Amibiase",
    "examens_obligatoires": ["Sérologie amibiase", "Échographie abdominale", "NFS", "Transaminases"],
    "medicament_1ere": "Métronidazole 750mg × 3/jour 10 jours",
    "medicament_2eme": "Tinidazole 2g/jour 5 jours + Tiliquinol si luminale",
    "examen_a_oublier": "Échographie abdominale",
    "contre_indication_profil_D": "Métronidazole déconseillé T1 grossesse"
  },
  {
    "id": "M53", "nom": "Giardiase",
    "profil_A": {"age": 4, "sexe": "F", "poids": 16, "ville": "Dakar", "cas_special": "enfant"},
    "profil_D": {"age": 2, "sexe": "H", "poids": 12, "ville": "Dakar", "cas_special": "enfant"},
    "diagnostic_attendu": "Giardiase",
    "examens_obligatoires": ["Examen parasitologique selles × 3", "Coproculture si doute"],
    "medicament_1ere": "Métronidazole 15mg/kg/jour 5 jours enfant",
    "medicament_2eme": "Tinidazole 50mg/kg dose unique",
    "examen_a_oublier": "Coproculture",
    "contre_indication_profil_D": "Adapter dose au poids 12kg"
  },
  {
    "id": "M54", "nom": "Colique néphrétique",
    "profil_A": {"age": 41, "sexe": "H", "poids": 77, "ville": "Abidjan", "cas_special": "aucun"},
    "profil_D": {"age": 35, "sexe": "F", "poids": 68, "ville": "Abidjan", "cas_special": "enceinte", "grossesse_trimestre": 2},
    "diagnostic_attendu": "Lithiase",
    "examens_obligatoires": ["BU + ECBU", "Créatinine", "NFS", "Échographie rénale", "Calcémie"],
    "medicament_1ere": "Kétoprofène 100mg IV + Phloroglucinol + Morphine si résistant",
    "medicament_2eme": "Tramadol si AINS contre-indiqués",
    "examen_a_oublier": "Calcémie",
    "contre_indication_profil_D": "AINS contre-indiqués T3 — Paracétamol + antispasmodique"
  },
  {
    "id": "M55", "nom": "Déshydratation sévère",
    "profil_A": {"age": 0, "sexe": "H", "poids": 7, "ville": "Lomé", "cas_special": "enfant", "mois": 8},
    "profil_D": {"age": 0, "sexe": "F", "poids": 5, "ville": "Lomé", "cas_special": "enfant", "mois": 5},
    "diagnostic_attendu": "Déshydratation",
    "examens_obligatoires": ["Ionogramme", "Créatinine", "Glycémie", "NFS"],
    "medicament_1ere": "Ringer Lactate 100ml/kg en 3h (plan C) puis SRO",
    "medicament_2eme": "Sérum physiologique si Ringer indisponible",
    "examen_a_oublier": "Ionogramme",
    "contre_indication_profil_D": "Volume calculé sur poids exact 5kg : 500ml en 3h"
  },
  {
    "id": "M56", "nom": "Hypoglycémie",
    "profil_A": {"age": 58, "sexe": "H", "poids": 82, "ville": "Yaoundé", "cas_special": "diabetique"},
    "profil_D": {"age": 70, "sexe": "F", "poids": 68, "ville": "Yaoundé", "cas_special": "diabetique"},
    "diagnostic_attendu": "Hypoglycémie",
    "examens_obligatoires": ["Glycémie capillaire", "Ionogramme", "Glycémie veineuse"],
    "medicament_1ere": "Glucose 30% 1 à 3 ampoules IV ou Glucagon 1mg IM si IV impossible",
    "medicament_2eme": "Perfusion Glucose 10% + collation après correction",
    "examen_a_oublier": "Ionogramme",
    "contre_indication_profil_D": "Surveillance rapprochée — adapter traitement diabète"
  },
  {
    "id": "M57", "nom": "État de choc septique",
    "profil_A": {"age": 44, "sexe": "F", "poids": 66, "ville": "Lagos", "cas_special": "aucun"},
    "profil_D": {"age": 72, "sexe": "H", "poids": 70, "ville": "Lagos", "cas_special": "aucun"},
    "diagnostic_attendu": "Choc septique",
    "examens_obligatoires": ["Hémocultures × 2", "NFS", "CRP", "Lactates", "Créatinine", "Transaminases", "Ionogramme"],
    "medicament_1ere": "Ceftriaxone 2g/12h IV + Métronidazole + remplissage 30ml/kg 3h",
    "medicament_2eme": "Noradrénaline si PAM < 65 mmHg malgré remplissage",
    "examen_a_oublier": "Lactates",
    "contre_indication_profil_D": "Remplissage prudent si insuffisance cardiaque"
  },
  {
    "id": "M58", "nom": "Convulsions fébriles",
    "profil_A": {"age": 2, "sexe": "H", "poids": 12, "ville": "Ouagadougou", "cas_special": "enfant"},
    "profil_D": {"age": 1, "sexe": "F", "poids": 9, "ville": "Ouagadougou", "cas_special": "enfant", "mois": 15},
    "diagnostic_attendu": "Convulsions",
    "examens_obligatoires": ["Glycémie capillaire", "TDR paludisme", "Ionogramme", "NFS", "PL si méningite"],
    "medicament_1ere": "Diazépam rectal 0.5mg/kg si crise > 5 min + Paracétamol",
    "medicament_2eme": "Phénobarbital IV 15mg/kg si résistant diazépam",
    "examen_a_oublier": "PL si méningite",
    "contre_indication_profil_D": "Adapter dose diazépam : 9kg → 4.5mg"
  },
  {
    "id": "M59", "nom": "Anaphylaxie",
    "profil_A": {"age": 25, "sexe": "H", "poids": 70, "ville": "Abidjan", "cas_special": "allergie", "allergie": "pénicilline"},
    "profil_D": {"age": 8, "sexe": "F", "poids": 25, "ville": "Abidjan", "cas_special": "enfant"},
    "diagnostic_attendu": "Anaphylaxie",
    "examens_obligatoires": ["Tryptase sérique", "NFS", "TA + oxymétrie"],
    "medicament_1ere": "Adrénaline 0.5mg IM cuisse + Décubitus + Oxygène",
    "medicament_2eme": "Antihistaminiques + Corticoïdes en 2ème intention",
    "examen_a_oublier": "Tryptase sérique",
    "contre_indication_profil_D": "Adapter dose adrénaline : 0.01mg/kg IM pour enfant"
  },
  {
    "id": "M60", "nom": "Dépression",
    "profil_A": {"age": 38, "sexe": "F", "poids": 62, "ville": "Kinshasa", "cas_special": "aucun"},
    "profil_D": {"age": 30, "sexe": "F", "poids": 58, "ville": "Kinshasa", "cas_special": "enceinte", "grossesse_trimestre": 1},
    "diagnostic_attendu": "Dépression",
    "examens_obligatoires": ["TSH", "NFS", "Glycémie", "Bilan hépatique", "Score PHQ-9"],
    "medicament_1ere": "Sertraline 50mg/jour puis 100mg/jour si toléré",
    "medicament_2eme": "Fluoxétine 20mg/jour si sertraline insuffisante",
    "examen_a_oublier": "TSH",
    "contre_indication_profil_D": "Sertraline possible T2-T3 · prudence T1 · psychothérapie 1ère intention"
  },
]

# Maladies avec erreur médecin fixe (toujours les mêmes pour comparabilité des runs)
MALADIES_ERREUR_FIXE = {"M1", "M4", "M7", "M21", "M29", "M55"}

# Maladies avec symptôme flou (profil C)
MALADIES_SYMPTOME_FLOU = {"M2", "M6", "M11", "M15", "M25", "M43"}
